### ISSUE TITLE
How to configure the webserver path in packtag instead of App server path?

### ISSUE THREAD

**Issue by inigoarulraj** [galan/packtag#10]
Hi ,
In my WCS project, we are using both web server and app servers, we are retrieving the js and css files from webserver location, but as per default setting in packtag, it is directly accessing the appserver location where the file is not found. is there any way to configure the path in any of the packtag property files?

**Comment by galan** [comment]
Sorry, WebSphere is not supported, as far as I remember it didn't implemented the specification correctly.
