### ISSUE TITLE
CSS feature calc(... not working

### ISSUE THREAD

**Issue by waldhow** [galan/packtag#11]
The calc() feature renders badly, which will lead to error in css file and calc will not be processed. 

**Without packtag:**
`width: calc(100% - (294px + (16px)));`

**With Packtag (no space after -):**
`width: calc(100% -(294px + (16px)));`

**Comment by waldhow** [comment]
From https://developer.mozilla.org/en-US/docs/Web/CSS/calc :

The + and - operators must always be surrounded by whitespace. The operand of calc(50% -8px) for instance will be parsed as a percentage followed by a negative length, an invalid expression, while the operand of calc(50% - 8px) is a percentage followed by a minus sign and a length. Even further, calc(8px + -50%) is treated as a length followed by a plus sign and a negative percentage.
The * and / operators do not require whitespace, but adding it for consistency is allowed, and recommended.

**Comment by galan** [comment]
All I can say is to try a different CSS pack strategy. I'm not working on the implementations, which are only integrated, and not developed by myself.
